### ISSUE TITLE
issueベースの開発 レビュー依頼

### ISSUE THREAD

**Issue by TaikiSakai** [TaikiSakai/langLog#12]
## 実装予定機能
- [x] ログイン機能
- [ ] プロフィール機能
- [ ] 単語帳機能
- [ ] ChatGPTによる動詞の自動活用機能
- [ ] 公開されている単語帳のランキング機能
- [ ] 学習記録機能

## 必要なページ
- [ ] トップページ
- [ ] ダッシュボード
- [ ] ログイン画面
- [ ] サインアップ画面
- [ ] プロフィール編集画面
- [ ] 単語帳一覧画面
- [ ] 単語帳画面
- [ ] 単語帳編集画面
- [ ] 学習記録画面
- [ ] タスク登録画面

**Comment by Tsuchiya2** [comment]
![image](https://github.com/TaikiSakai/langLog/assets/61481161/069b3788-a087-427a-b5b4-559cca7dc409)

Projectsにアクセスしてみましたが、看板・issue・ストーリーポイントが確認できませんでした。カリキュラムをご確認いただき、上記3つが確認できる状態で提出してください。

**Comment by TaikiSakai** [comment]
申し訳ございません。
priveteになっておりました。

**Comment by Tsuchiya2** [comment]
確認できました。
対応ありがとうございます。
以下コメントになります。

---

ストーリーポイント8, 5のものは、おそらく見通しが不鮮明な箇所があるのかと感じました。ストーリーポイント1,2くらいになるまで細かくissue化すると、何が分かっていて、何が不透明なのかが可視化されますし、ポイントの消化が容易になり進捗を感じながら開発を進められるかと思います。一度見直しをしてみましょう。

**Comment by tarakish** [comment]
https://github.com/TaikiSakai/langLog/issues/12#issuecomment-2048886734
こちら上記のTsuchiya講師以降のコメントが見当たらないので、変更を行ったのであればその旨を記載するようご確認をお願いします。

**Comment by TaikiSakai** [comment]
申し訳ございません、コメントが抜けておりました  

---
ストーリーポイントが5以上だった項目について修正しました
下記の実装内容についてタスクを細分化しました
#### 動詞活用機能
- chatGPTに送るjsonデータのserializerの定義
- chatGPTへ送るデータの抽出
- chatGPTのレスポンス処理

#### 学習記録機能
- データベースの定義
- 記録画面で表示するデータのapi
- 学習記録、編集画面

#### ダッシュボード
- 学習記録の見える化で表示するデータのapi
- 学習記録の表示画面

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。
