### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by TaikiSakai** [TaikiSakai/langLog#53]
## 各種情報
サービス名: langLog
サービスURL: https://lin-guardia.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- ログイン機能
- 学習記録
- 単語帳機能(動詞活用機能付き)

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

## READMEレビュー時から変更した機能
- 学習記録機能は機能見直しのためMVPからは除外しました
- TOPページは、搭載機能がもう少し明確になってから作成します

## 実装した機能
- ログイン機能
- 単語帳機能

ユーザー1人あたりのChatGPTの利用制限は本リリースにて対応します
データのフェッチが不安定な部分がありますが、本リリースにて対応します
データの更新をした際に更新されない場合はリロードしてください

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有をお願いします

## ログイン
[![Image from Gyazo](https://i.gyazo.com/690c89d3fd4b8ee2183b2c6377d94c1a.png)](https://gyazo.com/690c89d3fd4b8ee2183b2c6377d94c1a)

### デモ用アカウント
メールが届かず、アカウントが作成できない場合はこちらを使用してください
動詞自動活用機能はこちらから確認していただいた方がスムーズかと思います
- email: mvp-user@example.com
- password: mvpdesuyo

## サインアップ
[![Image from Gyazo](https://i.gyazo.com/e5367447f785e95d5d947f61fbf0ccc8.png)](https://gyazo.com/e5367447f785e95d5d947f61fbf0ccc8)

## 単語帳一覧ページ
[![Image from Gyazo](https://i.gyazo.com/0a5854f236a2a5b84ad9ba70d2a55fcf.png)](https://gyazo.com/0a5854f236a2a5b84ad9ba70d2a55fcf)

## 単語帳詳細ページ
[![Image from Gyazo](https://i.gyazo.com/34aea3d7be5def09696a64404a43bcf7.png)](https://gyazo.com/34aea3d7be5def09696a64404a43bcf7)

## 単語追加ページ
[![Image from Gyazo](https://i.gyazo.com/9084cb1c3f69c97b6d193108b978bfb8.png)](https://gyazo.com/9084cb1c3f69c97b6d193108b978bfb8)

## フラッシュカード
[![Image from Gyazo](https://i.gyazo.com/05a05bde03dbc9537d6cc4e04d1c8638.png)](https://gyazo.com/05a05bde03dbc9537d6cc4e04d1c8638)

## 動詞自動活用
[![Image from Gyazo](https://i.gyazo.com/2b6796e4195b4b3071d491bc3ec86c03.png)](https://gyazo.com/2b6796e4195b4b3071d491bc3ec86c03)

**Comment by Tsuchiya2** [comment]
ユーザー登録した際にメールアドレスにメールが届くらしいのですが、、、届かない状態です。一度ご確認をお願いいたします。

**Comment by TaikiSakai** [comment]
迷惑メールに入っていませんでしょうか

**Comment by TaikiSakai** [comment]
確認しましたが、存在しないアドレスを入力されているので届いていないようです。

**Comment by TaikiSakai** [comment]
![image](https://github.com/TaikiSakai/langLog/assets/135448782/e6335b34-c1bb-4dd2-b127-e46168424a31)
こちらのアドレスでよろしかったでしょうか？
迷惑メールにないかご確認お願いします。

**Comment by Tsuchiya2** [comment]
届いていませんでした。開発者以外の他者がログインできるように対応をお願いいたします。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
